# Generated by Django 3.1.6 on 2021-02-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('FaceImg', models.ImageField(blank=True, upload_to='')),
                ('DateBirth', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug_fil', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, db_index=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('Author', models.ManyToManyField(blank=True, related_name='authors', to='Polls.Author')),
                ('Genre', models.ManyToManyField(blank=True, related_name='authors', to='Polls.Genre')),
            ],
        ),
    ]
