# Generated by Django 3.1.6 on 2021-02-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='slug_fil',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='book',
            name='Genre',
            field=models.ManyToManyField(blank=True, related_name='Genres', to='Polls.Genre'),
        ),
    ]
