# Generated by Django 3.1.6 on 2021-02-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distros',
            name='ver',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
