# Generated by Django 3.1.5 on 2021-02-06 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0003_auto_20210206_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Genre',
        ),
        migrations.AddField(
            model_name='author',
            name='Genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Polls.genre'),
            preserve_default=False,
        ),
    ]
