# Generated by Django 3.1.5 on 2021-02-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0004_auto_20210206_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='FaceImg',
            field=models.ImageField(blank=True, upload_to='Media/Images/'),
        ),
    ]
