# Generated by Django 3.1.5 on 2021-02-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0005_author_faceimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Genre',
        ),
    ]
