# Generated by Django 3.1.5 on 2021-02-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0006_remove_author_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='Write_date',
        ),
    ]
