# Generated by Django 3.1.6 on 2021-02-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0007_remove_books_write_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='FaceImg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='books',
            name='Author',
        ),
        migrations.AddField(
            model_name='books',
            name='Author',
            field=models.ManyToManyField(to='Polls.Author'),
        ),
        migrations.RemoveField(
            model_name='books',
            name='Genre',
        ),
        migrations.AddField(
            model_name='books',
            name='Genre',
            field=models.ManyToManyField(to='Polls.Genre'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
